// Code generated by lister-gen. DO NOT EDIT.

package v1

// NetworkAttachmentDefinitionListerExpansion allows custom methods to be added to
// NetworkAttachmentDefinitionLister.
type NetworkAttachmentDefinitionListerExpansion interface{}

// NetworkAttachmentDefinitionNamespaceListerExpansion allows custom methods to be added to
// NetworkAttachmentDefinitionNamespaceLister.
type NetworkAttachmentDefinitionNamespaceListerExpansion interface{}
