// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/danm-cni/danm/crd/client/nad/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// NetworkAttachmentDefinitions returns a NetworkAttachmentDefinitionInformer.
	NetworkAttachmentDefinitions() NetworkAttachmentDefinitionInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// NetworkAttachmentDefinitions returns a NetworkAttachmentDefinitionInformer.
func (v *version) NetworkAttachmentDefinitions() NetworkAttachmentDefinitionInformer {
	return &networkAttachmentDefinitionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
