// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/danm-cni/danm/crd/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterNetworks returns a ClusterNetworkInformer.
	ClusterNetworks() ClusterNetworkInformer
	// DanmEps returns a DanmEpInformer.
	DanmEps() DanmEpInformer
	// DanmNets returns a DanmNetInformer.
	DanmNets() DanmNetInformer
	// TenantConfigs returns a TenantConfigInformer.
	TenantConfigs() TenantConfigInformer
	// TenantNetworks returns a TenantNetworkInformer.
	TenantNetworks() TenantNetworkInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClusterNetworks returns a ClusterNetworkInformer.
func (v *version) ClusterNetworks() ClusterNetworkInformer {
	return &clusterNetworkInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// DanmEps returns a DanmEpInformer.
func (v *version) DanmEps() DanmEpInformer {
	return &danmEpInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DanmNets returns a DanmNetInformer.
func (v *version) DanmNets() DanmNetInformer {
	return &danmNetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TenantConfigs returns a TenantConfigInformer.
func (v *version) TenantConfigs() TenantConfigInformer {
	return &tenantConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TenantNetworks returns a TenantNetworkInformer.
func (v *version) TenantNetworks() TenantNetworkInformer {
	return &tenantNetworkInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
