// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/danm-cni/danm/crd/client/clientset/versioned/typed/danm/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDanmV1 struct {
	*testing.Fake
}

func (c *FakeDanmV1) ClusterNetworks() v1.ClusterNetworkInterface {
	return newFakeClusterNetworks(c)
}

func (c *FakeDanmV1) DanmEps(namespace string) v1.DanmEpInterface {
	return newFakeDanmEps(c, namespace)
}

func (c *FakeDanmV1) DanmNets(namespace string) v1.DanmNetInterface {
	return newFakeDanmNets(c, namespace)
}

func (c *FakeDanmV1) TenantConfigs() v1.TenantConfigInterface {
	return newFakeTenantConfigs(c)
}

func (c *FakeDanmV1) TenantNetworks(namespace string) v1.TenantNetworkInterface {
	return newFakeTenantNetworks(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDanmV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
