// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	danmv1 "github.com/danm-cni/danm/crd/client/clientset/versioned/typed/danm/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTenantConfigs implements TenantConfigInterface
type fakeTenantConfigs struct {
	*gentype.FakeClientWithList[*v1.TenantConfig, *v1.TenantConfigList]
	Fake *FakeDanmV1
}

func newFakeTenantConfigs(fake *FakeDanmV1) danmv1.TenantConfigInterface {
	return &fakeTenantConfigs{
		gentype.NewFakeClientWithList[*v1.TenantConfig, *v1.TenantConfigList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("tenantconfigs"),
			v1.SchemeGroupVersion.WithKind("TenantConfig"),
			func() *v1.TenantConfig { return &v1.TenantConfig{} },
			func() *v1.TenantConfigList { return &v1.TenantConfigList{} },
			func(dst, src *v1.TenantConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1.TenantConfigList) []*v1.TenantConfig { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.TenantConfigList, items []*v1.TenantConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
