// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	danmv1 "github.com/danm-cni/danm/crd/client/clientset/versioned/typed/danm/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDanmNets implements DanmNetInterface
type fakeDanmNets struct {
	*gentype.FakeClientWithList[*v1.DanmNet, *v1.DanmNetList]
	Fake *FakeDanmV1
}

func newFakeDanmNets(fake *FakeDanmV1, namespace string) danmv1.DanmNetInterface {
	return &fakeDanmNets{
		gentype.NewFakeClientWithList[*v1.DanmNet, *v1.DanmNetList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("danmnets"),
			v1.SchemeGroupVersion.WithKind("DanmNet"),
			func() *v1.DanmNet { return &v1.DanmNet{} },
			func() *v1.DanmNetList { return &v1.DanmNetList{} },
			func(dst, src *v1.DanmNetList) { dst.ListMeta = src.ListMeta },
			func(list *v1.DanmNetList) []*v1.DanmNet { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.DanmNetList, items []*v1.DanmNet) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
