// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	danmv1 "github.com/danm-cni/danm/crd/client/clientset/versioned/typed/danm/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterNetworks implements ClusterNetworkInterface
type fakeClusterNetworks struct {
	*gentype.FakeClientWithList[*v1.ClusterNetwork, *v1.ClusterNetworkList]
	Fake *FakeDanmV1
}

func newFakeClusterNetworks(fake *FakeDanmV1) danmv1.ClusterNetworkInterface {
	return &fakeClusterNetworks{
		gentype.NewFakeClientWithList[*v1.ClusterNetwork, *v1.ClusterNetworkList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("clusternetworks"),
			v1.SchemeGroupVersion.WithKind("ClusterNetwork"),
			func() *v1.ClusterNetwork { return &v1.ClusterNetwork{} },
			func() *v1.ClusterNetworkList { return &v1.ClusterNetworkList{} },
			func(dst, src *v1.ClusterNetworkList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ClusterNetworkList) []*v1.ClusterNetwork { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ClusterNetworkList, items []*v1.ClusterNetwork) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
