// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	danmv1 "github.com/danm-cni/danm/crd/client/clientset/versioned/typed/danm/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDanmEps implements DanmEpInterface
type fakeDanmEps struct {
	*gentype.FakeClientWithList[*v1.DanmEp, *v1.DanmEpList]
	Fake *FakeDanmV1
}

func newFakeDanmEps(fake *FakeDanmV1, namespace string) danmv1.DanmEpInterface {
	return &fakeDanmEps{
		gentype.NewFakeClientWithList[*v1.DanmEp, *v1.DanmEpList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("danmeps"),
			v1.SchemeGroupVersion.WithKind("DanmEp"),
			func() *v1.DanmEp { return &v1.DanmEp{} },
			func() *v1.DanmEpList { return &v1.DanmEpList{} },
			func(dst, src *v1.DanmEpList) { dst.ListMeta = src.ListMeta },
			func(list *v1.DanmEpList) []*v1.DanmEp { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.DanmEpList, items []*v1.DanmEp) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
