// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	danmv1 "github.com/danm-cni/danm/crd/client/clientset/versioned/typed/danm/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTenantNetworks implements TenantNetworkInterface
type fakeTenantNetworks struct {
	*gentype.FakeClientWithList[*v1.TenantNetwork, *v1.TenantNetworkList]
	Fake *FakeDanmV1
}

func newFakeTenantNetworks(fake *FakeDanmV1, namespace string) danmv1.TenantNetworkInterface {
	return &fakeTenantNetworks{
		gentype.NewFakeClientWithList[*v1.TenantNetwork, *v1.TenantNetworkList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("tenantnetworks"),
			v1.SchemeGroupVersion.WithKind("TenantNetwork"),
			func() *v1.TenantNetwork { return &v1.TenantNetwork{} },
			func() *v1.TenantNetworkList { return &v1.TenantNetworkList{} },
			func(dst, src *v1.TenantNetworkList) { dst.ListMeta = src.ListMeta },
			func(list *v1.TenantNetworkList) []*v1.TenantNetwork { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.TenantNetworkList, items []*v1.TenantNetwork) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
