// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	scheme "github.com/danm-cni/danm/crd/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterNetworksGetter has a method to return a ClusterNetworkInterface.
// A group's client should implement this interface.
type ClusterNetworksGetter interface {
	ClusterNetworks() ClusterNetworkInterface
}

// ClusterNetworkInterface has methods to work with ClusterNetwork resources.
type ClusterNetworkInterface interface {
	Create(ctx context.Context, clusterNetwork *danmv1.ClusterNetwork, opts metav1.CreateOptions) (*danmv1.ClusterNetwork, error)
	Update(ctx context.Context, clusterNetwork *danmv1.ClusterNetwork, opts metav1.UpdateOptions) (*danmv1.ClusterNetwork, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*danmv1.ClusterNetwork, error)
	List(ctx context.Context, opts metav1.ListOptions) (*danmv1.ClusterNetworkList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *danmv1.ClusterNetwork, err error)
	ClusterNetworkExpansion
}

// clusterNetworks implements ClusterNetworkInterface
type clusterNetworks struct {
	*gentype.ClientWithList[*danmv1.ClusterNetwork, *danmv1.ClusterNetworkList]
}

// newClusterNetworks returns a ClusterNetworks
func newClusterNetworks(c *DanmV1Client) *clusterNetworks {
	return &clusterNetworks{
		gentype.NewClientWithList[*danmv1.ClusterNetwork, *danmv1.ClusterNetworkList](
			"clusternetworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *danmv1.ClusterNetwork { return &danmv1.ClusterNetwork{} },
			func() *danmv1.ClusterNetworkList { return &danmv1.ClusterNetworkList{} },
		),
	}
}
