// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	scheme "github.com/danm-cni/danm/crd/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DanmNetsGetter has a method to return a DanmNetInterface.
// A group's client should implement this interface.
type DanmNetsGetter interface {
	DanmNets(namespace string) DanmNetInterface
}

// DanmNetInterface has methods to work with DanmNet resources.
type DanmNetInterface interface {
	Create(ctx context.Context, danmNet *danmv1.DanmNet, opts metav1.CreateOptions) (*danmv1.DanmNet, error)
	Update(ctx context.Context, danmNet *danmv1.DanmNet, opts metav1.UpdateOptions) (*danmv1.DanmNet, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*danmv1.DanmNet, error)
	List(ctx context.Context, opts metav1.ListOptions) (*danmv1.DanmNetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *danmv1.DanmNet, err error)
	DanmNetExpansion
}

// danmNets implements DanmNetInterface
type danmNets struct {
	*gentype.ClientWithList[*danmv1.DanmNet, *danmv1.DanmNetList]
}

// newDanmNets returns a DanmNets
func newDanmNets(c *DanmV1Client, namespace string) *danmNets {
	return &danmNets{
		gentype.NewClientWithList[*danmv1.DanmNet, *danmv1.DanmNetList](
			"danmnets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *danmv1.DanmNet { return &danmv1.DanmNet{} },
			func() *danmv1.DanmNetList { return &danmv1.DanmNetList{} },
		),
	}
}
