// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	http "net/http"

	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	scheme "github.com/danm-cni/danm/crd/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type DanmV1Interface interface {
	RESTClient() rest.Interface
	ClusterNetworksGetter
	DanmEpsGetter
	DanmNetsGetter
	TenantConfigsGetter
	TenantNetworksGetter
}

// DanmV1Client is used to interact with features provided by the danm.io group.
type DanmV1Client struct {
	restClient rest.Interface
}

func (c *DanmV1Client) ClusterNetworks() ClusterNetworkInterface {
	return newClusterNetworks(c)
}

func (c *DanmV1Client) DanmEps(namespace string) DanmEpInterface {
	return newDanmEps(c, namespace)
}

func (c *DanmV1Client) DanmNets(namespace string) DanmNetInterface {
	return newDanmNets(c, namespace)
}

func (c *DanmV1Client) TenantConfigs() TenantConfigInterface {
	return newTenantConfigs(c)
}

func (c *DanmV1Client) TenantNetworks(namespace string) TenantNetworkInterface {
	return newTenantNetworks(c, namespace)
}

// NewForConfig creates a new DanmV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*DanmV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new DanmV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*DanmV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &DanmV1Client{client}, nil
}

// NewForConfigOrDie creates a new DanmV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *DanmV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new DanmV1Client for the given RESTClient.
func New(c rest.Interface) *DanmV1Client {
	return &DanmV1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := danmv1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *DanmV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
