// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	scheme "github.com/danm-cni/danm/crd/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DanmEpsGetter has a method to return a DanmEpInterface.
// A group's client should implement this interface.
type DanmEpsGetter interface {
	DanmEps(namespace string) DanmEpInterface
}

// DanmEpInterface has methods to work with DanmEp resources.
type DanmEpInterface interface {
	Create(ctx context.Context, danmEp *danmv1.DanmEp, opts metav1.CreateOptions) (*danmv1.DanmEp, error)
	Update(ctx context.Context, danmEp *danmv1.DanmEp, opts metav1.UpdateOptions) (*danmv1.DanmEp, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*danmv1.DanmEp, error)
	List(ctx context.Context, opts metav1.ListOptions) (*danmv1.DanmEpList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *danmv1.DanmEp, err error)
	DanmEpExpansion
}

// danmEps implements DanmEpInterface
type danmEps struct {
	*gentype.ClientWithList[*danmv1.DanmEp, *danmv1.DanmEpList]
}

// newDanmEps returns a DanmEps
func newDanmEps(c *DanmV1Client, namespace string) *danmEps {
	return &danmEps{
		gentype.NewClientWithList[*danmv1.DanmEp, *danmv1.DanmEpList](
			"danmeps",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *danmv1.DanmEp { return &danmv1.DanmEp{} },
			func() *danmv1.DanmEpList { return &danmv1.DanmEpList{} },
		),
	}
}
