// Code generated by client-gen. DO NOT EDIT.

package v1

type ClusterNetworkExpansion interface{}

type DanmEpExpansion interface{}

type DanmNetExpansion interface{}

type TenantConfigExpansion interface{}

type TenantNetworkExpansion interface{}
