// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	scheme "github.com/danm-cni/danm/crd/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TenantConfigsGetter has a method to return a TenantConfigInterface.
// A group's client should implement this interface.
type TenantConfigsGetter interface {
	TenantConfigs() TenantConfigInterface
}

// TenantConfigInterface has methods to work with TenantConfig resources.
type TenantConfigInterface interface {
	Create(ctx context.Context, tenantConfig *danmv1.TenantConfig, opts metav1.CreateOptions) (*danmv1.TenantConfig, error)
	Update(ctx context.Context, tenantConfig *danmv1.TenantConfig, opts metav1.UpdateOptions) (*danmv1.TenantConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*danmv1.TenantConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*danmv1.TenantConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *danmv1.TenantConfig, err error)
	TenantConfigExpansion
}

// tenantConfigs implements TenantConfigInterface
type tenantConfigs struct {
	*gentype.ClientWithList[*danmv1.TenantConfig, *danmv1.TenantConfigList]
}

// newTenantConfigs returns a TenantConfigs
func newTenantConfigs(c *DanmV1Client) *tenantConfigs {
	return &tenantConfigs{
		gentype.NewClientWithList[*danmv1.TenantConfig, *danmv1.TenantConfigList](
			"tenantconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *danmv1.TenantConfig { return &danmv1.TenantConfig{} },
			func() *danmv1.TenantConfigList { return &danmv1.TenantConfigList{} },
		),
	}
}
