// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	scheme "github.com/danm-cni/danm/crd/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TenantNetworksGetter has a method to return a TenantNetworkInterface.
// A group's client should implement this interface.
type TenantNetworksGetter interface {
	TenantNetworks(namespace string) TenantNetworkInterface
}

// TenantNetworkInterface has methods to work with TenantNetwork resources.
type TenantNetworkInterface interface {
	Create(ctx context.Context, tenantNetwork *danmv1.TenantNetwork, opts metav1.CreateOptions) (*danmv1.TenantNetwork, error)
	Update(ctx context.Context, tenantNetwork *danmv1.TenantNetwork, opts metav1.UpdateOptions) (*danmv1.TenantNetwork, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*danmv1.TenantNetwork, error)
	List(ctx context.Context, opts metav1.ListOptions) (*danmv1.TenantNetworkList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *danmv1.TenantNetwork, err error)
	TenantNetworkExpansion
}

// tenantNetworks implements TenantNetworkInterface
type tenantNetworks struct {
	*gentype.ClientWithList[*danmv1.TenantNetwork, *danmv1.TenantNetworkList]
}

// newTenantNetworks returns a TenantNetworks
func newTenantNetworks(c *DanmV1Client, namespace string) *tenantNetworks {
	return &tenantNetworks{
		gentype.NewClientWithList[*danmv1.TenantNetwork, *danmv1.TenantNetworkList](
			"tenantnetworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *danmv1.TenantNetwork { return &danmv1.TenantNetwork{} },
			func() *danmv1.TenantNetworkList { return &danmv1.TenantNetworkList{} },
		),
	}
}
