// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/danm-cni/danm/crd/client/nad/clientset/versioned/typed/k8s.cni.cncf.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeK8sCniCncfIoV1 struct {
	*testing.Fake
}

func (c *FakeK8sCniCncfIoV1) NetworkAttachmentDefinitions(namespace string) v1.NetworkAttachmentDefinitionInterface {
	return newFakeNetworkAttachmentDefinitions(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeK8sCniCncfIoV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
