// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterNetworkLister helps list ClusterNetworks.
// All objects returned here must be treated as read-only.
type ClusterNetworkLister interface {
	// List lists all ClusterNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.ClusterNetwork, err error)
	// Get retrieves the ClusterNetwork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*danmv1.ClusterNetwork, error)
	ClusterNetworkListerExpansion
}

// clusterNetworkLister implements the ClusterNetworkLister interface.
type clusterNetworkLister struct {
	listers.ResourceIndexer[*danmv1.ClusterNetwork]
}

// NewClusterNetworkLister returns a new ClusterNetworkLister.
func NewClusterNetworkLister(indexer cache.Indexer) ClusterNetworkLister {
	return &clusterNetworkLister{listers.New[*danmv1.ClusterNetwork](indexer, danmv1.Resource("clusternetwork"))}
}
