// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DanmEpLister helps list DanmEps.
// All objects returned here must be treated as read-only.
type DanmEpLister interface {
	// List lists all DanmEps in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.DanmEp, err error)
	// DanmEps returns an object that can list and get DanmEps.
	DanmEps(namespace string) DanmEpNamespaceLister
	DanmEpListerExpansion
}

// danmEpLister implements the DanmEpLister interface.
type danmEpLister struct {
	listers.ResourceIndexer[*danmv1.DanmEp]
}

// NewDanmEpLister returns a new DanmEpLister.
func NewDanmEpLister(indexer cache.Indexer) DanmEpLister {
	return &danmEpLister{listers.New[*danmv1.DanmEp](indexer, danmv1.Resource("danmep"))}
}

// DanmEps returns an object that can list and get DanmEps.
func (s *danmEpLister) DanmEps(namespace string) DanmEpNamespaceLister {
	return danmEpNamespaceLister{listers.NewNamespaced[*danmv1.DanmEp](s.ResourceIndexer, namespace)}
}

// DanmEpNamespaceLister helps list and get DanmEps.
// All objects returned here must be treated as read-only.
type DanmEpNamespaceLister interface {
	// List lists all DanmEps in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.DanmEp, err error)
	// Get retrieves the DanmEp from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*danmv1.DanmEp, error)
	DanmEpNamespaceListerExpansion
}

// danmEpNamespaceLister implements the DanmEpNamespaceLister
// interface.
type danmEpNamespaceLister struct {
	listers.ResourceIndexer[*danmv1.DanmEp]
}
