// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DanmNetLister helps list DanmNets.
// All objects returned here must be treated as read-only.
type DanmNetLister interface {
	// List lists all DanmNets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.DanmNet, err error)
	// DanmNets returns an object that can list and get DanmNets.
	DanmNets(namespace string) DanmNetNamespaceLister
	DanmNetListerExpansion
}

// danmNetLister implements the DanmNetLister interface.
type danmNetLister struct {
	listers.ResourceIndexer[*danmv1.DanmNet]
}

// NewDanmNetLister returns a new DanmNetLister.
func NewDanmNetLister(indexer cache.Indexer) DanmNetLister {
	return &danmNetLister{listers.New[*danmv1.DanmNet](indexer, danmv1.Resource("danmnet"))}
}

// DanmNets returns an object that can list and get DanmNets.
func (s *danmNetLister) DanmNets(namespace string) DanmNetNamespaceLister {
	return danmNetNamespaceLister{listers.NewNamespaced[*danmv1.DanmNet](s.ResourceIndexer, namespace)}
}

// DanmNetNamespaceLister helps list and get DanmNets.
// All objects returned here must be treated as read-only.
type DanmNetNamespaceLister interface {
	// List lists all DanmNets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.DanmNet, err error)
	// Get retrieves the DanmNet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*danmv1.DanmNet, error)
	DanmNetNamespaceListerExpansion
}

// danmNetNamespaceLister implements the DanmNetNamespaceLister
// interface.
type danmNetNamespaceLister struct {
	listers.ResourceIndexer[*danmv1.DanmNet]
}
