// Code generated by lister-gen. DO NOT EDIT.

package v1

// ClusterNetworkListerExpansion allows custom methods to be added to
// ClusterNetworkLister.
type ClusterNetworkListerExpansion interface{}

// DanmEpListerExpansion allows custom methods to be added to
// DanmEpLister.
type DanmEpListerExpansion interface{}

// DanmEpNamespaceListerExpansion allows custom methods to be added to
// DanmEpNamespaceLister.
type DanmEpNamespaceListerExpansion interface{}

// DanmNetListerExpansion allows custom methods to be added to
// DanmNetLister.
type DanmNetListerExpansion interface{}

// DanmNetNamespaceListerExpansion allows custom methods to be added to
// DanmNetNamespaceLister.
type DanmNetNamespaceListerExpansion interface{}

// TenantConfigListerExpansion allows custom methods to be added to
// TenantConfigLister.
type TenantConfigListerExpansion interface{}

// TenantNetworkListerExpansion allows custom methods to be added to
// TenantNetworkLister.
type TenantNetworkListerExpansion interface{}

// TenantNetworkNamespaceListerExpansion allows custom methods to be added to
// TenantNetworkNamespaceLister.
type TenantNetworkNamespaceListerExpansion interface{}
