// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TenantNetworkLister helps list TenantNetworks.
// All objects returned here must be treated as read-only.
type TenantNetworkLister interface {
	// List lists all TenantNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.TenantNetwork, err error)
	// TenantNetworks returns an object that can list and get TenantNetworks.
	TenantNetworks(namespace string) TenantNetworkNamespaceLister
	TenantNetworkListerExpansion
}

// tenantNetworkLister implements the TenantNetworkLister interface.
type tenantNetworkLister struct {
	listers.ResourceIndexer[*danmv1.TenantNetwork]
}

// NewTenantNetworkLister returns a new TenantNetworkLister.
func NewTenantNetworkLister(indexer cache.Indexer) TenantNetworkLister {
	return &tenantNetworkLister{listers.New[*danmv1.TenantNetwork](indexer, danmv1.Resource("tenantnetwork"))}
}

// TenantNetworks returns an object that can list and get TenantNetworks.
func (s *tenantNetworkLister) TenantNetworks(namespace string) TenantNetworkNamespaceLister {
	return tenantNetworkNamespaceLister{listers.NewNamespaced[*danmv1.TenantNetwork](s.ResourceIndexer, namespace)}
}

// TenantNetworkNamespaceLister helps list and get TenantNetworks.
// All objects returned here must be treated as read-only.
type TenantNetworkNamespaceLister interface {
	// List lists all TenantNetworks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.TenantNetwork, err error)
	// Get retrieves the TenantNetwork from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*danmv1.TenantNetwork, error)
	TenantNetworkNamespaceListerExpansion
}

// tenantNetworkNamespaceLister implements the TenantNetworkNamespaceLister
// interface.
type tenantNetworkNamespaceLister struct {
	listers.ResourceIndexer[*danmv1.TenantNetwork]
}
