// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	danmv1 "github.com/danm-cni/danm/crd/apis/danm/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TenantConfigLister helps list TenantConfigs.
// All objects returned here must be treated as read-only.
type TenantConfigLister interface {
	// List lists all TenantConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*danmv1.TenantConfig, err error)
	// Get retrieves the TenantConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*danmv1.TenantConfig, error)
	TenantConfigListerExpansion
}

// tenantConfigLister implements the TenantConfigLister interface.
type tenantConfigLister struct {
	listers.ResourceIndexer[*danmv1.TenantConfig]
}

// NewTenantConfigLister returns a new TenantConfigLister.
func NewTenantConfigLister(indexer cache.Indexer) TenantConfigLister {
	return &tenantConfigLister{listers.New[*danmv1.TenantConfig](indexer, danmv1.Resource("tenantconfig"))}
}
